name: Unit tests
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: bpi-f3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure
        run: |
          cmake -B build -DBUILD_TESTS=1 -DBUILD_THUNKING=0 -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
      - name: Build
        run: |
          cmake --build build -j8
      - name: Test
        run: |
          ./build/felix86_test
          ./build/felix86 -k
